In [6]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
Af = np.array([1, 2, 3], float)

[[1 2 3]
 [4 5 6]]


In [9]:
print(np.arange(0, 1, 0.2))
print(np.linspace(0, 2*np.pi, 4))
A = np.zeros((2,3))
print(A)
A.shape

[0.  0.2 0.4 0.6 0.8]
[0.         2.0943951  4.1887902  6.28318531]
[[0. 0. 0.]
 [0. 0. 0.]]


(2, 3)

In [10]:
A = np.ones((3,3))
print(3 * A - 1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [12]:
u = [1, 2, 3]
v = [1, 1, 1]
print(np.inner(u, v))
print(np.outer(u, v))
print(np.dot(u, v))

6
[[1 1 1]
 [2 2 2]
 [3 3 3]]
6


In [13]:
A = np.ones((3, 2))
print(A)
print(A.T)
B = np.ones((2, 3))
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
